# Generated by Django 4.2.3 on 2023-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='공지사항', max_length=30),
        ),
    ]
